version: '3'
services:
  video_db:
    image: mongo:latest
    container_name: "video_db"
    environment: 
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27017:27017"
    volumes:
      - /home/gokul/volumes/vid_io:/data/db
